### ISSUE TITLE
Unable to merge

### ISSUE THREAD

**Issue by JhinSir** [christiandeange/aaraar#11]
When I use this plugin for aar output, build went wrong:

Unknown dependency type: C:\Users\admin\xxx\xxx\xxx\build\intermediates\aar\release\bundleReleaseAar\out

This is my config：
plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.jetbrains.kotlin.android)
    //alias(libs.plugins.aaraar)
    id "sh.christian.aaraar" version "0.0.16"
}

aaraar {
    isEnabledForVariant { variant ->
        variant.name == "release"
    }
}

**Comment by christiandeange** [comment]
Which version of `libs.plugins.android.library` are you using?

**Comment by JhinSir** [comment]
> 您正在使用哪个版本？`libs.plugins.android.library`

7.3.1

**Comment by JhinSir** [comment]
> > 您正在使用哪个版本？`libs.plugins.android.library`
> 
> 7.3.1

After I upgraded to 8.4, I found that I could build normally. However, after the build was completed, the third-party dependency libraries in lirbrary were not merged and output. I did not find the rx and okhttp libraries I depended on.

**Comment by JhinSir** [comment]
aaraar {
    isEnabledForVariant { variant ->
        variant.name == "release"
    }
}
When I only configured this configuration, I found that the dependencies were not merged and output！！！
But after I used embed, I found that it can indeed be merged.
Maybe I misunderstood. Embled is not provided by the higher version of AGP, but by your plugin!! fat-aar?

**Comment by christiandeange** [comment]
> When I only configured this configuration, I found that the dependencies were not merged and output！！！
> But after I used embed, I found that it can indeed be merged.
> Maybe I misunderstood. Embled is not provided by the higher version of AGP, but by your plugin!! fat-aar?

Yes that's right, please read the user guide for instructions on how to configure the plugin: https://aaraar.christian.sh/packaging/

I will investigate the issue with using AGP 7.3.1, but it sounds like you are unblocked when using AGP 8.4?

**Comment by JhinSir** [comment]
> > 当我只配置这个配置时，我发现依赖项没有被合并和输出!!但是我用了embed之后，发现它确实可以被合并。也许我误会了。Embled 不是由 AGP 的更高版本提供的，而是由您的插件提供的！！胖啊？
> 
> 是的，没错，请阅读用户指南以获取有关如何配置插件的说明： https://aaraar.christian.sh/packaging/
> 
> 我将调查使用 AGP 7.3.1 的问题，但听起来您在使用 AGP 8.4 时没有被阻止？

**Comment by JhinSir** [comment]
> > > 当我只配置这个配置时，我发现依赖项没有被合并和输出!!但是我用了embed之后，发现它确实可以被合并。也许我误会了。Embled 不是由 AGP 的更高版本提供的，而是由您的插件提供的！！胖啊？
> > 
> > 
> > 是的，没错，请阅读用户指南以获取有关如何配置插件的说明： https://aaraar.christian.sh/packaging/
> > 我将调查使用 AGP 7.3.1 的问题，但听起来您在使用 AGP 8.4 时没有被阻止？

Yes, no problem with 8.4.
