### ISSUE TITLE
Embed dependencies in Pom file

### ISSUE THREAD

**Issue by GMCristiano** [christiandeange/aaraar#2]
README states that "Dependencies marked as api will be included as compile dependencies in the published pom file. **embed dependencies will be included as runtime in the pom.**"

After merging AARs, i think dependencies embed don't actually need to be included in the POM file for Maven to know about because the embed dependency will be inside main-library.aar and code inside classes.jar as expected.

Right know i'm getting this errors when using a Maven Local with the embed dependencies included in POM.

```
<dependency>
      <groupId>Example</groupId>
      <artifactId>example-lib</artifactId>
      <version>1.0.0</version>
      <scope>runtime</scope>
</dependency>
```
-Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find Example:example-lib:1.0.0.

-Could not find Example:example-lib:1.0.0 - file:/Users/username/.m2/repository/Example/example-lib/1.0.0/example-lib-1.0.0.pom.

My workaround to put everything working temporary:
-Remove embed dependency from POM file because embed dependency will be inside main-library.aar as expected. 
-Disabling Gradle Module Metadata publication to only use changed POM file without configuration conflicts.

I'm not sure if i'm doing something wrong.
Hope this helps

**Comment by christiandeange** [comment]
Hmm, I think you might be right on this one. Especially since classes in some of those `embed` dependencies could be shaded, leading to different class names.

I'll experiment with this over the weekend.

**Comment by christiandeange** [comment]
Actually I think the README might be wrong. If I do the following:

```groovy
dependencies {
  implementation 'io.reactivex.rxjava3:rxjava:3.1.5'
  embed 'io.reactivex.rxjava3:rxjava:3.1.5'
}
```

I do actually see this showing up in the final POM:

```xml
<dependency>
  <groupId>io.reactivex.rxjava3</groupId>
  <artifactId>rxjava</artifactId>
  <version>3.1.5</version>
  <scope>runtime</scope>
</dependency>
```

But if I replace that `implementation` with a `compileOnly`, it disappears. So I think that the `embed` configurations (correctly) don't contribute to the dependencies metadata, but the README incorrectly claims that 😅 will fix that!
