### ISSUE TITLE
Missing files in final AAR file

### ISSUE THREAD

**Issue by GMCristiano** [christiandeange/aaraar#6]
If we compare a normal publish with a publish using this plugin, I noticed that some comum files are not included. 
The files are just meta information and libraries works anyway, but I don't know if this can impact libraries with importantes root configuration files from android/google.

1. MEATA-INF/com/android/build/gradle/aar-metadata.properties (any lib)

Content example:
```
aarFormatVersion=1.0
aarMetadataVersion=1.0
minCompileSdk=1
minCompileSdkExtension=0
minAndroidGradlePluginVersion=1.0.0
```

2. navigation.json (lib using navigation component)

Content example:
```
[
  {
    "name": "name_navigation",
    "navigationXmlIds": [],
    "deepLinks": []
  }
]
```

**Comment by christiandeange** [comment]
The latest `0.0.9-SNAPSHOT` should now preserve both of these:
- If present, `aar-metadata.properties` will simply be copied from the library module that the plugin is being run on
- Entries in any `navigation.json` files will be merged from any `embed` dependencies into the merged `aar` file.
