### ISSUE TITLE
Problems with multiple jar packages

### ISSUE THREAD

**Issue by GuoLiangjun123** [christiandeange/aaraar#7]
What if I want to generate multiple jars at the same time, and each jar has a different package name

**Comment by christiandeange** [comment]
This doesn't concern aaraar. If you want to generate multiple jars, you need to configure custom build types or product flavors. You can then configure a different application id for each of them by setting the `applicationIdSuffix` property.

See https://developer.android.com/build/build-variants#change-app-id for more details.
