### ISSUE TITLE
META-INF from classes.jar not merged

### ISSUE THREAD

**Issue by GMCristiano** [christiandeange/aaraar#8]
I find out that classes.jar with META-INF folder with content files, nothing is merged.

In Kotlin this is important for files with global functions.

Example of file name generated in classes.jar:  META-INF/exampe_release.kotlin_module

**Comment by christiandeange** [comment]
Have you configured the gradle extension to keep `META-INF/` files in the merged jar?

```kotlin
plugins {
  id("sh.christian.aaraar") version "0.0.10"
}

aaraar {
  keepMetaFiles.set(true)
}
```

**Comment by GMCristiano** [comment]
Oh, no. i will check that on monday.

But it's not present in your public documentation ;)

**Comment by christiandeange** [comment]
Oops, yeah I don't really mention it in the docs 😅 will make sure I change that!

**Comment by GMCristiano** [comment]
it's working. thx

**Comment by christiandeange** [comment]
Version `0.0.11` now defaults `keepMetaFiles` to true, so you won't need to explicitly set it anymore.

Also added a small note for this field in https://aaraar.christian.sh/packaging
